export const SLUGS: Record<string, string> = {
  'Cerf élaphe': 'cerf-elaphe',
  'Chevreuil': 'chevreuil',
  'Sanglier': 'sanglier',
  'Daim': 'daim',
  'Cerf sika': 'cerf-sika',
  'Chamois': 'chamois',
  'Mouflon méditerranéen': 'mouflon-mediterraneen',
  'Tétras-lyre': 'tetras-lyre',
  'Lagopède alpin': 'lagopede-alpin',
  'Perdrix bartavelle': 'perdrix-bartavelle',
  'Grand tétras': 'grand-tetras',
  'Gélinotte des bois': 'gelinotte-bois',
  'Lièvre variable': 'lievre-variable',
  'Marmotte': 'marmotte',
  "Lièvre d'Europe": 'lievre-europe',
  'Lapin de garenne': 'lapin-garenne',
  'Perdrix rouge': 'perdrix-rouge',
  'Perdrix grise': 'perdrix-grise',
  'Faisan commun': 'faisan-commun',
  'Colin de Virginie': 'colin',
  'Bécasse des bois': 'becasse-bois',
  'Caille des blés': 'caille-bles',
  'Grive draine': 'grive-draine',
  'Grive litorne': 'grive-litorne',
  'Grive mauvis': 'grive-mauvis',
  'Grive musicienne': 'grive-musicienne',
  'Merle noir': 'merle-noir',
  'Alouette des champs': 'alouette-champs',
  'Pigeon ramier': 'pigeon-ramier',
  'Pigeon colombin': 'pigeon-colombin',
  'Pigeon biset': 'pigeon-biset',
  'Tourterelle turque': 'tourterelle-turque',
  'Tourterelle des bois': 'tourterelle-bois',
  'Canard colvert': 'canard-colvert',
  'Canard chipeau': 'canard-chipeau',
  'Canard siffleur': 'canard-siffleur',
  'Canard pilet': 'canard-pilet',
  'Canard souchet': 'canard-souchet',
  "Sarcelle d'hiver": 'sarcelle-hiver',
  "Sarcelle d'été": 'sarcelle-ete',
  'Fuligule milouin': 'fuligule-milouin',
  'Fuligule morillon': 'fuligule-morillon',
  'Fuligule milouinan': 'fuligule-milouinan',
  'Nette rousse': 'nette-rousse',
  "Garrot à œil d'or": 'garrot-oeil-dor',
  'Harelde boréale': 'harelde-boreale',
  'Macreuse brune': 'macreuse-brune',
  'Macreuse noire': 'macreuse-noire',
  'Eider à duvet': 'eider-a-duvet',
  'Oie cendrée': 'oie-cendree',
  'Oie rieuse': 'oie-rieuse',
  'Oie des moissons': 'oie-moissons',
  'Foulque macroule': 'foulque-macroule',
  "Poule d'eau": 'poule-eau',
  "Râle d'eau": 'rale-eau',
  'Bécassine des marais': 'becassine-marais',
  'Bécassine sourde': 'becassine-sourde',
  'Barge rousse': 'barge-rousse',
  'Barge à queue noire': 'barge-queue-noire',
  'Bécasseau maubèche': 'becasseau-maubeche',
  'Chevalier aboyeur': 'chevalier-aboyeur',
  'Chevalier arlequin': 'chevalier-arlequin',
  'Chevalier combattant': 'chevalier-combattant',
  'Chevalier gambette': 'chevalier-gambette',
  'Courlis corlieu': 'courlis-corlieu',
  'Courlis cendré': 'courlis-cendre',
  'Huîtrier pie': 'huitrier-pie',
  'Pluvier doré': 'pluvier-dore',
  'Pluvier argenté': 'pluvier-argente',
  'Vanneau huppé': 'vanneau-huppe',
  'Renard roux': 'renard',
  'Fouine': 'fouine',
  'Martre des pins': 'martre',
  "Putois d'Europe": 'putois',
  "Belette d'Europe": 'belette',
  'Corneille noire': 'corneille-noire',
  'Corbeau freux': 'corbeau-freux',
  'Pie bavarde': 'pie-bavarde',
  'Geai des chênes': 'geai-chenes',
  'Étourneau sansonnet': 'etourneau',
  'Ragondin': 'ragondin',
  'Rat musqué': 'rat-musque',
  'Chien viverrin': 'chien-viverrin',
  "Vison d'Amérique": 'vison-amerique',
  'Raton laveur': 'raton-laveur',
  'Bernache du Canada': 'bernache-canada',
  'Tangue': 'tangue',
  'Lièvre à collier noir': 'lievre-collier-noir',
  'Cerf de Java': 'cerf-de-java',
};
